import { Component } from "@angular/core";
import { ICustomer } from "src/app/model/customer";
import { Router } from "@angular/router";

@Component({
  selector: "app-customers",
  templateUrl: "./customers.component.html",
  styleUrls: ["./customers.component.css"],
})
export class CustomersComponent {
  constructor(private router: Router) {}
  goToNext() {
    // this.router.navigate(["dashboard/initiators-details"]);
    this.router.navigate(["/app/initiators-details"]);
  }

  customers: ICustomer[] = [
    {
      CUSTOMER_NUMBER: "23423",
      SHORT_NAME: "SHORT.NAME1673948",
      IS_INDIVIDUAL: "Y",
      NATIONALITY: "MU",
      NATIONALITY_NUMBER: "480",
      NATIONALITY_DESCRIPTION: "MAURITIUS",
      STREET_ADDRESS: "STREET-ADDR",
      ADDRESS_LINE2: ["Royal Road"],
      ADDRESS_LINE3: [],
      TOWN_COUNTRY: "SURINAM",
      POST_CODE: ["7444"],
      COUNTRY: "COUNTRY",
      COUNTRY_CODE: "MU",
      COUNTRY_CODE_NUMBER: "480",
      DISPATCH_CODE: "MA",
      COMMUNICATION_CHANNEL: "BY EMAIL",
      PHONE_NUMBER: "22222222",
      OFFICE_PHONE_NUMBER: "33333333",
      FAX_NUMBER: "258974661",
      MOBILE_OPERATORISO: "48",
      MOBILE_OPERATOR_CODE: "ORANGEMU",
      SMS_NUMBER: "+230123456789",
      EMAIL: "THIS_IS_A_TEST@GMAIL.COM",
    },
    // Add 5 more customer objects
    {
      CUSTOMER_NUMBER: "45678",
      SHORT_NAME: "SHORT.NAME45678",
      IS_INDIVIDUAL: "N",
      NATIONALITY: "US",
      NATIONALITY_NUMBER: "840",
      NATIONALITY_DESCRIPTION: "UNITED STATES",
      STREET_ADDRESS: "123 Main St",
      ADDRESS_LINE2: ["Suite 100"],
      ADDRESS_LINE3: [],
      TOWN_COUNTRY: "New York",
      POST_CODE: ["10001"],
      COUNTRY: "United States",
      COUNTRY_CODE: "US",
      COUNTRY_CODE_NUMBER: "840",
      DISPATCH_CODE: "NY",
      COMMUNICATION_CHANNEL: "BY PHONE",
      PHONE_NUMBER: "555-555-5555",
      OFFICE_PHONE_NUMBER: "666-666-6666",
      FAX_NUMBER: "123456789",
      MOBILE_OPERATORISO: "01",
      MOBILE_OPERATOR_CODE: "Verizon",
      SMS_NUMBER: "+15551234567",
      EMAIL: "example@example.com",
    },
    {
      CUSTOMER_NUMBER: "78910",
      SHORT_NAME: "SHORT.NAME78910",
      IS_INDIVIDUAL: "Y",
      NATIONALITY: "CA",
      NATIONALITY_NUMBER: "124",
      NATIONALITY_DESCRIPTION: "CANADA",
      STREET_ADDRESS: "789 Elm St",
      ADDRESS_LINE2: [],
      ADDRESS_LINE3: [],
      TOWN_COUNTRY: "Toronto",
      POST_CODE: ["M5V 2V5"],
      COUNTRY: "Canada",
      COUNTRY_CODE: "CA",
      COUNTRY_CODE_NUMBER: "124",
      DISPATCH_CODE: "ON",
      COMMUNICATION_CHANNEL: "BY EMAIL",
      PHONE_NUMBER: "777-777-7777",
      OFFICE_PHONE_NUMBER: "888-888-8888",
      FAX_NUMBER: "987654321",
      MOBILE_OPERATORISO: "02",
      MOBILE_OPERATOR_CODE: "Bell",
      SMS_NUMBER: "+17771234567",
      EMAIL: "example2@example.com",
    },
    {
      CUSTOMER_NUMBER: "111213",
      SHORT_NAME: "SHORT.NAME111213",
      IS_INDIVIDUAL: "N",
      NATIONALITY: "AU",
      NATIONALITY_NUMBER: "036",
      NATIONALITY_DESCRIPTION: "AUSTRALIA",
      STREET_ADDRESS: "456 King St",
      ADDRESS_LINE2: ["Level 5"],
      ADDRESS_LINE3: [],
      TOWN_COUNTRY: "Sydney",
      POST_CODE: ["2000"],
      COUNTRY: "Australia",
      COUNTRY_CODE: "AU",
      COUNTRY_CODE_NUMBER: "036",
      DISPATCH_CODE: "NSW",
      COMMUNICATION_CHANNEL: "BY PHONE",
      PHONE_NUMBER: "999-999-9999",
      OFFICE_PHONE_NUMBER: "000-000-0000",
      FAX_NUMBER: "135792468",
      MOBILE_OPERATORISO: "03",
      MOBILE_OPERATOR_CODE: "Telstra",
      SMS_NUMBER: "+19991234567",
      EMAIL: "example3@example.com",
    },
    {
      CUSTOMER_NUMBER: "141516",
      SHORT_NAME: "SHORT.NAME141516",
      IS_INDIVIDUAL: "Y",
      NATIONALITY: "GB",
      NATIONALITY_NUMBER: "826",
      NATIONALITY_DESCRIPTION: "UNITED KINGDOM",
      STREET_ADDRESS: "789 High St",
      ADDRESS_LINE2: ["Flat 3B"],
      ADDRESS_LINE3: [],
      TOWN_COUNTRY: "London",
      POST_CODE: ["SW1A 1AA"],
      COUNTRY: "United Kingdom",
      COUNTRY_CODE: "GB",
      COUNTRY_CODE_NUMBER: "826",
      DISPATCH_CODE: "LDN",
      COMMUNICATION_CHANNEL: "BY EMAIL",
      PHONE_NUMBER: "444-444-4444",
      OFFICE_PHONE_NUMBER: "555-555-5555",
      FAX_NUMBER: "246813579",
      MOBILE_OPERATORISO: "04",
      MOBILE_OPERATOR_CODE: "EE",
      SMS_NUMBER: "+44441234567",
      EMAIL: "example4@example.com",
    },
    {
      CUSTOMER_NUMBER: "171819",
      SHORT_NAME: "SHORT.NAME171819",
      IS_INDIVIDUAL: "N",
      NATIONALITY: "JP",
      NATIONALITY_NUMBER: "392",
      NATIONALITY_DESCRIPTION: "JAPAN",
      STREET_ADDRESS: "321 Sakura St",
      ADDRESS_LINE2: ["Building 7F"],
      ADDRESS_LINE3: [],
      TOWN_COUNTRY: "Tokyo",
      POST_CODE: ["100-0001"],
      COUNTRY: "Japan",
      COUNTRY_CODE: "JP",
      COUNTRY_CODE_NUMBER: "392",
      DISPATCH_CODE: "TYO",
      COMMUNICATION_CHANNEL: "BY PHONE",
      PHONE_NUMBER: "333-333-3333",
      OFFICE_PHONE_NUMBER: "444-444-4444",
      FAX_NUMBER: "369258147",
      MOBILE_OPERATORISO: "05",
      MOBILE_OPERATOR_CODE: "NTT",
      SMS_NUMBER: "+33331234567",
      EMAIL: "example5@example.com",
    },
  ];
}
