import { Component } from "@angular/core";
import { Customer } from "src/app/model/customer";
import { Router } from "@angular/router";

@Component({
  selector: "app-customers",
  templateUrl: "./customers.component.html",
  styleUrls: ["./customers.component.css"],
})
export class CustomersComponent {
  constructor(private router: Router) {}
  goToNext() {
    // this.router.navigate(["dashboard/initiators-details"]);
    this.router.navigate(["/app/initiators-details"]);
  }

  customers: Customer[] = [
    {
      customerNumber: "23423",
      shortName: "SHORT.NAME1673948",
      individual: true,
      nationality: "MU",
      nationalityNumber: "480",
      nationalityDescription: "MAURITIUS",
      streetAddress: "STREET-ADDR",
      addressLine2: "Royal Road",
      addressLine3: "",
      townCountry: "SURINAM",
      postCode: 7444,
      country: "Nigeria",
      countryCode: "MU",
      countryCodeNumber: "480",
      dispatchCode: "MA",
      communicationChannel: "BY email",
      phoneNumber: "22222222",
      officePhoneNumber: "33333333",
      faxNumber: "258974661",
      mobileOperatorISO: "48",
      mobileOperatorCode: "ORANGEMU",
      smsNumber: "+230123456789",
      email: "THIS_IS_A_TEST@GMAIL.COM",
    },
    // Add 5 more customer objects
    {
      customerNumber: "45678",
      shortName: "SHORT.NAME45678",
      individual: false,
      nationality: "US",
      nationalityNumber: "840",
      nationalityDescription: "UNITED STATES",
      streetAddress: "123 Main St",
      addressLine2: "Suite 100",
      addressLine3: "",
      townCountry: "New York",
      postCode: 10001,
      country: "United States",
      countryCode: "US",
      countryCodeNumber: "840",
      dispatchCode: "NY",
      communicationChannel: "BY PHONE",
      phoneNumber: "555-555-5555",
      officePhoneNumber: "666-666-6666",
      faxNumber: "123456789",
      mobileOperatorISO: "01",
      mobileOperatorCode: "Verizon",
      smsNumber: "+15551234567",
      email: "example@example.com",
    },
    {
      customerNumber: "78910",
      shortName: "SHORT.NAME78910",
      individual: true,
      nationality: "CA",
      nationalityNumber: "124",
      nationalityDescription: "CANADA",
      streetAddress: "789 Elm St",
      addressLine2: "",
      addressLine3: "",
      townCountry: "Toronto",
      postCode: 50005,
      country: "Canada",
      countryCode: "CA",
      countryCodeNumber: "124",
      dispatchCode: "ON",
      communicationChannel: "BY email",
      phoneNumber: "777-777-7777",
      officePhoneNumber: "888-888-8888",
      faxNumber: "987654321",
      mobileOperatorISO: "02",
      mobileOperatorCode: "Bell",
      smsNumber: "+17771234567",
      email: "example2@example.com",
    },
    {
      customerNumber: "111213",
      shortName: "SHORT.NAME111213",
      individual: false,
      nationality: "AU",
      nationalityNumber: "036",
      nationalityDescription: "AUSTRALIA",
      streetAddress: "456 King St",
      addressLine2: "Level 5",
      addressLine3: "",
      townCountry: "Sydney",
      postCode: 2000,
      country: "Australia",
      countryCode: "AU",
      countryCodeNumber: "036",
      dispatchCode: "NSW",
      communicationChannel: "BY PHONE",
      phoneNumber: "999-999-9999",
      officePhoneNumber: "000-000-0000",
      faxNumber: "135792468",
      mobileOperatorISO: "03",
      mobileOperatorCode: "Telstra",
      smsNumber: "+19991234567",
      email: "example3@example.com",
    },
    {
      customerNumber: "141516",
      shortName: "SHORT.NAME141516",
      individual: true,
      nationality: "GB",
      nationalityNumber: "826",
      nationalityDescription: "UNITED KINGDOM",
      streetAddress: "789 High St",
      addressLine2: "Flat 3B",
      addressLine3: "",
      townCountry: "London",
      postCode: 3457,
      country: "United Kingdom",
      countryCode: "GB",
      countryCodeNumber: "826",
      dispatchCode: "LDN",
      communicationChannel: "BY email",
      phoneNumber: "444-444-4444",
      officePhoneNumber: "555-555-5555",
      faxNumber: "246813579",
      mobileOperatorISO: "04",
      mobileOperatorCode: "EE",
      smsNumber: "+44441234567",
      email: "example4@example.com",
    },
    {
      customerNumber: "171819",
      shortName: "SHORT.NAME171819",
      individual: false,
      nationality: "JP",
      nationalityNumber: "392",
      nationalityDescription: "JAPAN",
      streetAddress: "321 Sakura St",
      addressLine2: "Building 7F",
      addressLine3: "",
      townCountry: "Tokyo",
      postCode: 1000001,
      country: "Japan",
      countryCode: "JP",
      countryCodeNumber: "392",
      dispatchCode: "TYO",
      communicationChannel: "BY PHONE",
      phoneNumber: "333-333-3333",
      officePhoneNumber: "444-444-4444",
      faxNumber: "369258147",
      mobileOperatorISO: "05",
      mobileOperatorCode: "NTT",
      smsNumber: "+33331234567",
      email: "example5@example.com",
    },
  ];
}
